"""Input monitor - stops live dictation on physical keyboard/mouse input.

Listens for keyboard and mouse input using pynput. Ignores keypresses
generated by xdotool (which types partial results) by checking a grace
period after the last programmatic typing call. Enter bypasses the grace
period but still respects the is_typing guard (xdotool can generate
Return via formatting commands like "new line"). Mouse clicks bypass
both guards since xdotool never generates them.
"""

import threading
import time

from pynput import keyboard, mouse


XDOTOOL_GRACE_PERIOD = 0.5  # seconds after last xdotool call to ignore keypresses
STARTUP_GRACE_PERIOD = 1.0  # seconds to ignore clicks after monitor starts

_STOP_KEYS = {keyboard.Key.enter}


class KeyboardMonitor:
    """Monitors for physical keyboard/mouse activity, ignoring programmatic typing."""

    def __init__(self, stop_event: threading.Event, typer) -> None:
        self._stop_event = stop_event
        self._typer = typer
        self._keyboard_listener = None
        self._mouse_listener = None
        self._started_at = 0.0

    def start(self) -> None:
        self._started_at = time.time()
        self._typer.last_typed_at = time.time()
        self._keyboard_listener = keyboard.Listener(on_press=self._on_key_press)
        self._keyboard_listener.daemon = True
        self._keyboard_listener.start()
        self._mouse_listener = mouse.Listener(on_click=self._on_click)
        self._mouse_listener.daemon = True
        self._mouse_listener.start()

    def stop(self) -> None:
        if self._keyboard_listener is not None:
            self._keyboard_listener.stop()
        if self._mouse_listener is not None:
            self._mouse_listener.stop()

    def _on_key_press(self, key) -> None:
        if self._typer.is_typing:
            return
        if key in _STOP_KEYS:
            self._stop_event.set()
            return
        elapsed = time.time() - self._typer.last_typed_at
        if elapsed <= XDOTOOL_GRACE_PERIOD:
            return
        self._stop_event.set()

    def _on_click(self, _x, _y, _button, pressed) -> None:
        if not pressed:
            return
        if time.time() - self._started_at <= STARTUP_GRACE_PERIOD:
            return
        self._stop_event.set()
