"""Keyboard monitor - stops live dictation when the user types.

Listens for physical keyboard input using pynput. Ignores keypresses
generated by xdotool (which types partial results) by checking a grace
period after the last programmatic typing call.
"""

import threading
import time

from pynput import keyboard


XDOTOOL_GRACE_PERIOD = 0.5  # seconds after last xdotool call to ignore keypresses


class KeyboardMonitor:
    """Monitors for physical keyboard activity, ignoring programmatic typing."""

    def __init__(self, stop_event: threading.Event, typer) -> None:
        self._stop_event = stop_event
        self._typer = typer
        self._listener = None

    def start(self) -> None:
        self._typer.last_typed_at = time.time()
        self._listener = keyboard.Listener(on_press=self._on_key_press)
        self._listener.daemon = True
        self._listener.start()

    def stop(self) -> None:
        if self._listener is not None:
            self._listener.stop()

    def _on_key_press(self, key) -> None:
        elapsed = time.time() - self._typer.last_typed_at
        if elapsed > XDOTOOL_GRACE_PERIOD:
            self._stop_event.set()
